# Generated by Django 4.2.20 on 2025-03-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.AddField(
            model_name='category',
            name='category_fav_icon',
            field=models.TextField(default='fa-solid fa-icons', max_length=100),
        ),
    ]
